# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'golang-poc-img'

steps:
  - script: |
      docker build -f Dockerfile -t $(imageName) .
      docker login -u admin -p Harbor12345 13.94.30.68:3000
      docker push $(imageName)
